print ('Hello there!')
print ('What is your name?')
myName = input ()
print ('Good to meet you, ' + myName)
print ('The length of your name is: ' + str(len(myName)))
nameLength = str(len (myName))
print (nameLength + ' is my favorite number!')
myAge = input ('What is your age? ')
print ('You will be ' + str(int(myAge) + 1) + ' in a year!')